[ERROR] [2021-01-14 18:21:43,429:Client-AutoML(1):boston] Dummy prediction failed with run state StatusType.CRASHED and additional output: {'error': 'Result queue is empty', 'exit_status': 0, 'subprocess_stdout': 'Exception handling in `fit_predict_try_except_decorator`: traceback: Traceback (most recent call last):\n  File "/home/jackson/anaconda3/envs/automl/lib/python3.6/site-packages/autosklearn/evaluation/__init__.py", line 32, in fit_predict_try_except_decorator\n    return ta(queue=queue, **kwargs)\n  File "/home/jackson/anaconda3/envs/automl/lib/python3.6/site-packages/autosklearn/evaluation/train_evaluator.py", line 1079, in eval_holdout\n    evaluator.fit_predict_and_loss(iterative=iterative)\n  File "/home/jackson/anaconda3/envs/automl/lib/python3.6/site-packages/autosklearn/evaluation/train_evaluator.py", line 620, in fit_predict_and_loss\n    status=status,\n  File "/home/jackson/anaconda3/envs/automl/lib/python3.6/site-packages/autosklearn/evaluation/abstract_evaluator.py", line 333, in finish_up\n    self.queue.put(rval_dict)\n  File "/home/jackson/anaconda3/envs/automl/lib/python3.6/multiprocessing/queues.py", line 87, in put\n    self._start_thread()\n  File "/home/jackson/anaconda3/envs/automl/lib/python3.6/multiprocessing/queues.py", line 169, in _start_thread\n    self._thread.start()\n  File "/home/jackson/anaconda3/envs/automl/lib/python3.6/threading.py", line 846, in start\n    _start_new_thread(self._bootstrap, ())\nRuntimeError: can\'t start new thread\n \nerror message: RuntimeError("can\'t start new thread",)\n', 'subprocess_stderr': '', 'exitcode': 0, 'configuration_origin': 'DUMMY'}.
